const types = {
  SET_JOBS: 'SET_JOBS',
  SET_PROFILES: 'SET_PROFILES',
  SET_JOB: 'SET_JOB',
  SET_PROFILE: 'SET_PROFILE',
  SET_STATUS: 'SET_STATUS',
  SET_ERRORS: 'SET_ERRORS',
  SET_SEARCH: 'SET_SEARCH',
};

export default types;
